name: Update

on:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'pomerium/enterprise-client'
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: ${{ github.head_ref }}
          submodules: "true"
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Update
        run: |
          ./scripts/update

      - name: Commit
        uses: devops-infra/action-commit-push@e6a24fad602d1f92e46432c89a7e0c7fdd45d62d
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "ci: update"
